version: "3.8"

services:
  mongodb:
    container_name: image-serving-mongodb
    image: mongo:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
  backend:
    container_name: image-serving-backend
    depends_on:
      - mongodb
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mongodb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
    stdin_open: true
    tty: true
    volumes:
      - "./src:/usr/app/image-serving-api/src"

volumes:
  db: